CREATE DATABASE LOJA;
USE LOJA;
CREATE TABLE USUARIO(
	IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	LOGIN VARCHAR(30),
	SENHA VARCHAR(100)
);
CREATE TABLE BKP_USUARIO(
	IDBACKUP INT PRIMARY KEY AUTO_INCREMENT,
	IDUSUARIO INT,
	NOME VARCHAR(30),
	LOGIN VARCHAR(30)
);

CREATE TABLE PRODUTO (
IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT, 
DESCRICAO VARCHAR(50),
ESTOQUE INT);

CREATE TABLE VENDA (
IDVENDA INT PRIMARY KEY AUTO_INCREMENT,
FKPRODUTO INT,
QUANTIDADE INT,
FOREIGN KEY(FKPRODUTO) references PRODUTO(IDPRODUTO)
);

DELIMITER $
CREATE TRIGGER BACKUP_USER
BEFORE DELETE ON USUARIO
FOR EACH ROW 
BEGIN		
	INSERT INTO BKP_USUARIO VALUES
	(NULL,OLD.IDUSUARIO,OLD.NOME,OLD.LOGIN);
END
$

DELIMITER $
CREATE TRIGGER ATUALIZASALDO
AFTER INSERT ON VENDA
FOR  EACH ROW
BEGIN
DECLARE SALDO INT;
SELECT ESTOQUE FROM PRODUTO INTO SALDO;
UPDATE PRODUTO SET ESTOQUE = SALDO - NEW.QUANTIDADE WHERE IDPRODUTO = NEW.FKPRODUTO;
END 
$

DELIMITER $
CREATE TRIGGER ATUALIZASALDO2
AFTER INSERT ON VENDA
FOR  EACH ROW
BEGIN
	UPDATE PRODUTO 
    SET ESTOQUE = ESTOQUE - NEW.QUANTIDADE 
    WHERE IDPRODUTO = NEW.FKPRODUTO;
END 
$


INSERT INTO USUARIO VALUES (NULL, 'IURY', 'IURY', '1234')

DELETE FROM USUARIO WHERE IDUSUARIO = 1

SELECT * FROM BKP_USUARIO