COMANDOS BÁSICOS

/* DML (Data Manipulation Language) 
para representar o conjunto de instruções da linguagem SQL para manipular os dados(BANCO DE DADOS).
*/
/* CRIAÇÃO DE BANCO DE DADOS */
CREATE DATABASE ESCOLA;

/* SELECIONAR UM BANCO DE DADOS */
USE ESCOLA;

/* LISTAR BANCOS DE DADOS */
SHOW DATABASES;

/* EXCLUIR UM BANCO DE DADOS */
DROP DATABASE ESCOLA;


/*DDL (Data Definition Language) conjunto de instruções e comandos para definição de dados(TABELAS). */
/* CRIAÇÃO DE TABELAS */
CREATE TABLE ALUNO (
 ID_ALUNO INT PRIMARY KEY AUTO_INCREMENT,
 NOME VARCHAR(30)
 );
 
 CREATE TABLE PROFESSOR (
 ID_PROFESSOR INT PRIMARY KEY AUTO_INCREMENT,
 NOME VARCHAR(30)
 );
 
 CREATE TABLE AULA (
 ID_AULA INT PRIMARY KEY AUTO_INCREMENT,
 FK_ALUNO INT,
 FK_PROFESSOR INT, 
 FOREIGN KEY(FK_ALUNO) REFERENCES ALUNO(ID_ALUNO),
 FOREIGN KEY(FK_PROFESSOR) REFERENCES  PROFESSOR(ID_PROFESSOR)
 );

/* DETALHAR DE TABELAS */
 DESC AULA;
 
 /* EXCLUSÃO DE TABELAS */
 DROP TABLE NOMEDATABELA;
 
 /* ALTERAÇÃO DE TABELAS */
 
 
 